name: Create Development Builds

jobs:
  build_development_ios:
    type: build # This job type creates a development build for iOS
    params:
      platform: ios
      profile: development
  
  build_development_android:
    type: build # This job type creates a development build for Android
    params:
      platform: android
      profile: development
